### ISSUE TITLE
Reminder Function

### ISSUE THREAD

**Issue by str0mbolo** [User-r00/bravetraveler-issues#12]
A command that would remind a person to do something in a certain number of minutes/hours. [eg .remind 30 min]

**Comment by User-r00** [comment]
Mod approved. I'll start on it tonight.

**Comment by User-r00** [comment]
Implemented in https://github.com/User-r00/bravetraveler/pull/22.

**Comment by User-r00** [comment]
Merged to master.

**Comment by User-r00** [comment]
Pushed to server. Closing.
